### ISSUE TITLE
gracefully handle missing files/directories in cache storage

### ISSUE THREAD

**Issue by paveldikov** [astral-sh/uv#6147]
Not sure if this is a common pattern, but we like to store the cache directory on `/var/tmp` as the usual home directory may be on a network share (and extremely slow I/O as a result).

This works great for us, but it also happens that `/var/tmp` is affected by a periodic cleanup process that deletes old files/directories. Once this happens, we get a bunch of error messages along the lines of:

```
  Caused by: Failed to install: packaging-24.1-py3-none-any.http.whl (packaging==24.1)
  Caused by: failed to read directory `/var/tmp/pavel/.cache/uv/archive-v0/REDACTED`
  Caused by: No such file or directory (os error 2)
```

`rm -rf`'ing the cache dir (or `uv cache clean` -- but not `uv cache prune`) seems to work around this problem fine, but it's quite a severe thing to do.

**Comment by charliermarsh** [comment]
Agree, I think we should be robust to this. I don't know if we can be robust to `/var/tmp` being cleaned up _while_ uv is running though.

**Comment by paveldikov** [comment]
I think catching ENOENT and friends (at arbitrary depth?) and re-caching the distribution from scratch should be robust enough? I am trying to think of the various types of race conditions in there, but assuming that the hardlinking/copying into venv comes right at the end, this should be reasonably complete.

(symlink mode will not be helped by this, but that is probably fine?)

**Comment by paveldikov** [comment]
Heads up, I am seeing possible regressions on this one. I wonder if it may be worth adding an integration test for this scenario:
1. do a `uv pip install` of some skeleton package (iirc a bunch of these already exist as test fixtures)
2. then vandalise the cache by removing one of the files
3. `uv pip install --reinstall` it. It should succeed and the removed file should be present in the installation.

**Comment by charliermarsh** [comment]
Sounds good to me. Feel free to file an issue for any regression that you've seen.

**Comment by charliermarsh** [comment]
I'll add a few tests.

**Comment by charliermarsh** [comment]
I don’t know that we should necessarily aim to support these scenarios. Scenarios in which users modify the cache seem out of scope, and should be fixed by uv cache clean (as opposed to prune). What we _do_ want to be robust to are, e.g., changes in the cache schema, or any states that can result from running uv commands.

**Comment by paveldikov** [comment]
It's a synthetic reproduction of a real-life scenario, whereby a daemon process (e.g. `tmpwatch`) prunes files from a cache directory based on some coarse-grained criterion such as mtime/ctime.

I would agree that _mutating_ files would be out of scope, though.

**Comment by paveldikov** [comment]
Ok, I had a deeper dive with the code and the problem is complicated by `tmpwatch`'s behaviour in that it will delete files but not directories.  It is the 'deleting a given archive in isolation' that will trigger this problem -- I have a test case written for it which I can push out.

Applying the same treatment to the _whole_ cache dir appears to sidestep the issue, presumably because some top-level lookup table is also wiped out -- and therefore everything registers as a cache miss. However, IRL this is not likely to happen as the top-level lookup table will usually have a much more recent `mtime` because it is the common denominator in all cache operations.

So I am now stuck trying to do either of:
1. Prevent the cache lookup from picking up 'skeleton' archive entries -- this is proving difficult because it appears that the cache mechanics are type-agnostic and unaware of archive semantics/`dist-info`. Also I'd be worried about performance impact if I was to add elements of look-before-you-leap
2. Introduce a mechanism whereby we can safely backtrack on `ENOENT` -- this is proving difficult because the call stack is yay-deep and this would be extremely invasive in terms of function signatures 😰

(Unfortunately in my organisation I can't quite sidestep `tmpwatch`, so that's sadly not an option)

**Comment by sandyharvie** [comment]
This issue is still present for URL-based installation. Below, we see archive SbyXsev7P7Rs0BnG7u6TH was pruned at 2026-04-06T14:09:26 by a prune invocation that began at 2026-04-06T14:09:24 and completed successfully at 2026-04-06T14:09:28.
```
2026-04-06T14:09:24 DEBUG uv 0.11.2 (x86_64-unknown-linux-gnu)                                                                                               
2026-04-06T14:09:24 TRACE Checking lock for `/uv/cache` at `/uv/cache/.lock`                                                                                 
2026-04-06T14:09:24 TRACE Acquired exclusive lock for `/uv/cache`                                                                                            
2026-04-06T14:09:24 Pruning cache at: /uv/cache
...
2026-04-06T14:09:26 DEBUG Removing dangling cache archive: /uv/cache/archive-v0/SbyXsev7P7Rs0BnG7u6TH
...
2026-04-06T14:09:28 Removed 56646 files (6.5GiB)
2026-04-06T14:09:28 TRACE Released lock at `/uv/cache/.lock`
```
Quite some time later, this non-existent archive is somehow referenced during installation and the error in question is thus triggered.
```
2026-04-07T20:26:48 DEBUG uv 0.11.3 (x86_64-unknown-linux-gnu)
2026-04-07T20:26:48 TRACE Checking lock for `/uv/cache` at `/uv/cache/.lock`
2026-04-07T20:26:48 TRACE Acquired shared lock for `/uv/cache`
2026-04-07T20:26:48 DEBUG Checking for Python interpreter at path `/uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8/bin/python`
2026-04-07T20:26:48 TRACE Found cached interpreter info for Python 3.13.12, skipping query of: /uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8/bin/python
2026-04-07T20:26:48 Using Python 3.13.12 environment at: /uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8
2026-04-07T20:26:48 TRACE Checking lock for `/uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8` at `/uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8/.lock`
2026-04-07T20:26:48 TRACE Acquired exclusive lock for `/uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8`
...
2026-04-07T20:26:48 DEBUG Path wheel requirement already cached: rpds-py==0.27.1 (from file:///<redacted>/rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
2026-04-07T20:26:48 TRACE Released lock at `/uv/venvs/8a14338ed7004da5bf0ce65791a6de6a5b807fea4902a8502704f75bca606bf8/.lock`                                
2026-04-07T20:26:48 TRACE Released lock at `/uv/cache/.lock`                                                                                                 
2026-04-07T20:26:48 TRACE Error trace: Failed to install: rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (rpds-py==0.27.1 (from file:///<redacted>/rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl))                                                 
2026-04-07T20:26:48                                                                                                                                          
2026-04-07T20:26:48 Caused by:                                                                                                                               
2026-04-07T20:26:48     failed to read directory `/uv/cache/archive-v0/SbyXsev7P7Rs0BnG7u6TH`: No such file or directory (os error 2)                        
2026-04-07T20:26:48 error: Failed to install: rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (rpds-py==0.27.1 (from file:///<redacted>/rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl))
```

How a pruned archive can remain referenced is obviously a problem, seeing as an absence of references is a precondition for pruning, but I've not figured out how to reproduce that component of the issue. I have, however, determined that the cache is not robust to removed archives that were created by URL-based installation. Running the following Bash, we can see that normal installation is robust to archive removal:
```sh
VENV_DIR=$(mktemp -p /var/tmp -d)
uv venv $VENV_DIR --python 3.13
source ${VENV_DIR}/bin/activate

export UV_CACHE_DIR=$(mktemp -p /var/tmp -d)
uv pip install rpds-py==0.27.1
uv pip uninstall rpds-py
rm -rf ${UV_CACHE_DIR}/archive-v0
uv pip install rpds-py==0.27.1
```

If we change this Bash to install the same package from a particular URL, however, it fails:
```sh
VENV_DIR=$(mktemp -p /var/tmp -d)
uv venv $VENV_DIR --python 3.13
source ${VENV_DIR}/bin/activate

WHEEL_URL='https://files.pythonhosted.org/packages/03/36/0a14aebbaa26fe7fab4780c76f2239e76cc95a0090bdb25e31d95c492fcd/rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

export UV_CACHE_DIR=$(mktemp -p /var/tmp -d)
uv pip install $WHEEL_URL
uv pip uninstall rpds-py
rm -rf ${UV_CACHE_DIR}/archive-v0
uv pip install $WHEEL_URL
```

**Comment by sandyharvie** [comment]
It seems my issue is related to the .http files created as part of URL-based installation, since the following Bash completes successfully:
```sh
VENV_DIR=$(mktemp -p /var/tmp -d)
uv venv $VENV_DIR --python 3.13
source ${VENV_DIR}/bin/activate

WHEEL_URL='https://files.pythonhosted.org/packages/03/36/0a14aebbaa26fe7fab4780c76f2239e76cc95a0090bdb25e31d95c492fcd/rpds_py-0.27.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

export UV_CACHE_DIR=$(mktemp -p /var/tmp -d)
uv pip install $WHEEL_URL
uv pip uninstall rpds-py
rm -rf ${UV_CACHE_DIR}/archive-v0
rm ${UV_CACHE_DIR}/wheels-*/url/*/rpds-py/*.http
uv pip install $WHEEL_URL
```
