### ISSUE TITLE
[feat] uv publish --skip-existing

### ISSUE THREAD

**Issue by chassing** [astral-sh/uv#7917]
It would be great if `uv publish` had a `--skip-existing` option that ignores errors from files already on PyPI, similar to poetry's and twine's `--skip-existing` options.

**Comment by konstin** [comment]
Do you have a specific case that fails? `uv publish` already ignores it if you try to upload the same file again.

**Comment by chassing** [comment]
Mmmmhhh strange, I got this error:

```
10:57:30 uv build
10:57:30 Building source distribution...
10:57:30 Building wheel from source distribution...
10:57:30 Successfully built dist/rh_aws_saml_login-0.3.4.tar.gz and dist/rh_aws_saml_login-0.3.4-py3-****-any.whl
10:57:30 uv publish
10:57:30 warning: `uv publish` is experimental and may change without warning
10:57:30 Publishing 2 files https://upload.pypi.org/legacy/
10:57:30 Uploading rh_aws_saml_login-0.3.4-py3-****-any.whl (3.7KiB)
10:57:30 error: Failed to publish `dist/rh_aws_saml_login-0.3.4-py3-****-any.whl` to https://upload.pypi.org/legacy/
10:57:30   Caused by: Upload failed with status code 400 Bad Request: 400 File already exists ('rh_aws_saml_login-0.3.4-py3-****-any.whl', with blake2_256 hash '6c36e28fc15545d4e3d10a0c68e9d476afdb6ae2facdbb846a10098516575d0d'). See https://pypi.org/help/#file-name-reuse for more information.
10:57:30 make: *** [Makefile:39: pypi] Error 2
```

**Comment by chassing** [comment]
I'm sorry. Our development and release flow is the following: Users create PRs, and each PR is merged into the main branch. The main branch is automatically built and published to PyPI. As long nobody bumps the version number in `pyproject.toml`, we don't want to publish (release) a new version. We used `poetry` in the past, and the `--skip-existing` option did the job.

**Comment by TiansuYu** [comment]
> Do you have a specific case that fails? `uv publish` already ignores it if you try to upload the same file aga

No it doesn't. UV will try to upload all pre-existing ones. 

e.g. if I have published version 1.0.0, now wants to build and publish 1.0.1 locally, it it will try to upload 1.0.0 as well. I have to manually remove the older versions to make it work.

**Comment by konstin** [comment]
> e.g. if I have published version 1.0.0, now wants to build and publish 1.0.1 locally, it it will try to upload 1.0.0 as well. I have to manually remove the older versions to make it work.

Are these 1.0.0 files the same that are on the index, and when uploading, do you get a "already exists but ok" message or do you get an error?

**Comment by davidszotten** [comment]
for the ci workflow @chassing mentioned (which is similar to what we use) the files aren't necessarily identical. they point is to use "this file already exists in the index" as a shorthand for "version hasn't changed, no need to upload" (by treating that specific error as being ok). i ported the twine approach to poetry, it's based on some heuristics https://github.com/pypa/twine/blob/ae71822a3cb0478d0f6a0cccb65d6f8e6275ece5/twine/commands/upload.py#L58-L72 so a bit hacky, but it works very well in practice

**Comment by TiansuYu** [comment]
So I can verify that if the file is identical, the `uv publish` will pass, but will break if the code changes. And there is no info on "already exists but ok" 
<img width="636" alt="Screenshot 2024-10-04 at 17 21 48" src="https://github.com/user-attachments/assets/a342a9b0-71a3-4ad4-ade2-ae5c1b9cb4c5">
`uv 0.4.18 (7b55e9790 2024-10-01)`

**Comment by charliermarsh** [comment]
@konstin -- Where did we land on this?

**Comment by zanieb** [comment]
It seems problematic to try to upload different content and expect it to be treated the same way as uploading an identical file? It also seems reasonable to opt-in to ignoring failures in that case? Unless we want to add a command to check if a matching version exists or something?

**Comment by charliermarsh** [comment]
Yeah agree, which would lead us to adding a skip existing flag IIUC.

**Comment by davidszotten** [comment]
(if you decide to accept the feature request i'd be interested in having a go at implementing it (with some pointers))

**Comment by konstin** [comment]
> e.g. if I have published version 1.0.0, now wants to build and publish 1.0.1 locally, it it will try to upload 1.0.0 as well. I have to manually remove the older versions to make it work.

We could take a similar approach as `poetry publish` here and require the project's pyproject.toml to be present (either in the current directory or as part of the workspace), then only upload the version defined there. This would change CI workflows in some cases because it requires a checkout step for the publish step (e.g. if you build multiple wheels for different platforms, then collect and upload in a separate job, that job needs a checkout too).

**Comment by davidszotten** [comment]
i agree that the current implementations are a bit of a hack (and from your detailed description, perhaps even dangerous). just a note that the proposal of checking version against `pyproject.toml` doesn't satisfy mine (or op's i think) use-case of using skip-existing as a proxy for "was the version just bumped". (i'm open to ideas of other ways of achieving this though)

**Comment by TiansuYu** [comment]
In my workflow, I would also need to generate a dev version on the fly and publish a random dev version on every merge to main. Please also keep this in mind, when you devise `uv publish`.

**Comment by konstin** [comment]
@TiansuYu Could you expand on your overall workflow, i.e. how does the wheel get its random dev tag and where/how does this wheel from main get used?

**Comment by TiansuYu** [comment]
I would somehow edit the version string e.g. `1.0.0` -> `1.0.0.dev0` (using a script or something, or if uv can offer something like `uv version dev` kinda like `poetry version patch` but append a random version string.) Then run `uv build` and `uv publish`. This is what I mean.

**Comment by zanieb** [comment]
I also use a "publish development release on main" pattern

https://github.com/zanieb/poetry-relax/blob/5706001e383a2f3327f4ab7c2ced2b57d39e287a/.github/workflows/build.yaml#L51-L60

https://github.com/zanieb/poetry-relax/blob/5706001e383a2f3327f4ab7c2ced2b57d39e287a/scripts/version#L21-L25

**Comment by JohnPaton** [comment]
Popping in to say I'm affected by this. We run a monorepo and all packages are built when a tag is pushed, but the tag doesn't change the version of all packages because of prefixing. So it tries to publish all built packages, but not all of them have a new version. `twine`'s skip existing means that only the genuine changes are published. `uv` in its current state gives

```console
$ uv publish
warning: `uv publish` is experimental and may change without warning
Publishing 10 files https://index.company.com/...
Uploading my_pkg-0.2.1.dev136+g27f686d-py3-none-any.whl (2.4KiB)
error: Failed to publish `dist/my_pkg-0.2.1.dev136+g27f686d-py3-none-any.whl` to https://index.company.com/...
  Caused by: Upload failed with status code 403 Forbidden. Server says: {
  "errors" : [ {
    "status" : 403,
    "message" : "Not enough permissions to delete/overwrite artifact 'index:my_pkg/0.2.1.dev136+g27f686d/my_pkg-0.2.1.dev136+g27f686d-py3-none-any.whl' (user: 'user' needs DELETE permission)."
  } ]
}
```

I could build a script to check which build are changed compared to the index and only publish those ones, but whyh would I when `twine upload --skip-existing` exists.

**Comment by charliermarsh** [comment]
Did you look at `--check-index` support? https://github.com/astral-sh/uv/pull/8531

**Comment by fwallacevt** [comment]
Hey @charliermarsh we are impacted by this as well - `--check-url` is surprising in how it works in that it will _error if the file exists and does not match the local hash._ This is fundamentally different than how we expect something akin to `--skip-existing` to work. With `--check-url`, we get an error `error: Local file and index file do not match`. The expected behavior is that if the filename exists in the index we've pointed `uv` to, it should exit successfully.

**Comment by fwallacevt** [comment]
@charliermarsh we're using `uv` workspaces, and right now we run `uv build ... --all`, then publish everything that is built. What would you suggest as an alternative to only build packages if they should be built (e.g. version has changed)? Or is there another way you envision this workflow?

**Comment by konstin** [comment]
I'd recommend explicitly selecting the package(s) that changed and you want to publish. I know it's more effort than having the index figure it out, but it avoids publishing inconsistent sets of distributions for a version.

**Comment by fwallacevt** [comment]
@konstin @charliermarsh are you open to making this an optional feature? E.g. adding a flag that dictates whether a conflict results in a warning or an error?

**Comment by CobaltCause** [comment]
Another option might be to use different exit codes for `uv publish` to be able to make "local and remote hash don't match" and "some other error occurred" programmatically distinct errors. Then, for this use case, the exit code could be checked and ignored only if it's the "local and remote hash don't match" case. `uv publish || true` would work as-is but it risks ignoring the "some other error occurred" cases which is not great.

**Comment by joasode** [comment]
I agree that the default functionality of `uv publish` should return an error when the hash of the remote and local wheel has changed. However, we're trying to follow the recommended [publishing CI/CD](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) using `uv publish`, where a standard procedure is to publish to the testpypi index on every pull request. This seems to not currently be possible with `uv` due to _Local file and index file do not match_.

**Comment by Sylphe88** [comment]
We also need this option so our CI can publish the same package version with different content (over different CI executions). We use semver to version our packages and do not allow replacing an existing production packages (1.2.3) however our build/publish tools must allow for this for development versions (1.2.3a0 or 1.2.3.dev0 for instance) which we don't mind to change over time

**Comment by dbux** [comment]
> * GitLab: When uploading a file with the same name, you get a “400 Bad request - Validation failed: File name has already been taken”, no matter whether the file was identical or not.

This is the issue that's affecting us. As far as I can tell the current best solution is to delete the `dist/` directory after every publish action, which isn't ideal.

**Comment by pcgeek86** [comment]
Ugh, I ran into this problem because the folder name of my git repository was different than the Python package name on PyPi.
After I fixed the package name in `pyproject.toml`, the error continued to happen, because there was a `.whl` in the `dist` directory.
I had to manually clear that out, to get `uv` to publish the package properly.


```
error: Failed to publish `dist\trevor_py-0.1.0-py3-none-any.whl` to https://upload.pypi.org/legacy/
  Caused by: Upload failed with status code 403 Forbidden. Server says: 403 Invalid API Token: project-scoped token is not valid for project: 'trevor-py', project-scoped token is not valid for project: 'trevor-py'
```

My Python package is called `trevor`, not `trevor-py`, but my git repository is named `trevor-py`. I don't want them to match.

To be clear: I would **not** have expected `uv` to continue attempting to publish the package under the old name, after I fixed the package name in `pyproject.toml`.

**Comment by konstin** [comment]
What command(s) are you using? What is the contents of your `dist` directory? Please provide a minimal reproduction (https://github.com/astral-sh/uv/issues/9452).

**Comment by pcgeek86** [comment]
> What command(s) are you using? What is the contents of your `dist` directory? Please provide a minimal reproduction ([#9452](https://github.com/astral-sh/uv/issues/9452)).

```
mkdir testmod && cd testmod
uv init .
uv build

# Change pyproject.toml [project.name] to 'testmod02'

uv build  # Build package with new name

# Now your ./dist folder has:

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           7/17/2025 12:47 PM              1 .gitignore
-a---           7/17/2025 12:47 PM           1219 testmod-0.1.0-py3-none-any.whl
-a---           7/17/2025 12:47 PM            866 testmod-0.1.0.tar.gz
-a---           7/17/2025 12:47 PM           1238 testmod02-0.1.0-py3-none-any.whl
-a---           7/17/2025 12:47 PM            898 testmod02-0.1.0.tar.gz

# If you try to publish, it will attempt to publish all of the files in ./dist. 

uv publish --token <mytoken>

# Unfortunately there is no publish --dry-run parameter, so I cannot exactly reproduce the output unless I were to create a new package on PyPi
```

**Comment by konstin** [comment]
You need to remove the old files from `dist` (i.e., `rm -r dist`) after renaming the project, uv does not clear the `dist` directory automatically to not remove files that may still be used.

**Comment by linde12** [comment]
I'm a bit confused - i can see PRs adding `--check-url` but i am unable to get it working as expected (according to https://github.com/astral-sh/uv/pull/8531)

I've got the following config in my repo (with a subpackage using uv workspaces):

```toml
[[tool.uv.index]]
name = "myindex"
default = true
url = "https://myindex/path/to/pypi/PYPI/simple"
publish-url = "https://myindex/path/to/pypi/somerepo"
```

But i'm still getting hash mismatch in my CI when doing `uv build --all-packages` and `uv publish --index myindex` when i have changes in e.g. the subpackage that i have not bumped (that i don't want to release yet)

My CI pipeline is very simple (does not need to be more complex) - i simply want to build everything and publish any version that does not already exist.

[The docs for --check-url](https://docs.astral.sh/uv/reference/settings/#check-url) and the description of the linked PR differ a bit. Reading the docs, it looks to be the expected (but IMO less useful) behavior - e.g. it will always check hash and fail if the same version exists on the remote index.

If this is by design, does anyone have an example of a release workflow that manually publishes only new versions?

**Comment by konstin** [comment]
This is by design, it ensures that changed packages with the same version are treated differently, to avoid ghost-publishing where it looks like a package was updated, when it was just ignored.

> But i'm still getting hash mismatch in my CI when doing `uv build --all-packages` and `uv publish --index myindex` when i have changes in e.g. the subpackage that i have not bumped (that i don't want to release yet)

Can you inspect the build package, what is the difference with the previous build of the package that it changed hash?

**Comment by linde12** [comment]
@konstin Sorry, what is by design? What the docs state or what the PR states? Because to me, they state two different behaviors. I've manually modified "subpackage" but i have not updated the tag in it's pyproject.toml so i don't want to publish a new version, because the version already exists on my remote index. Then, i have a release workflow that always builds all packages and is supposed to publish only packages with versions that do not exist on the remote.

E.g. i guess i want something similar to the `--skip-existing` behavior of poetry which i though this issue was created to address, but i might've misunderstood or missed something? ☹️ 

If a built package, e.g. `subpackage==1.0.0`, already exist on the remote i just want to skip uploading it (no need to check the hash or anything in this case). This is because in my repo there might've been changes to `subpackage==1.0.0`, but it's version is not bumped yet (not to be released yet)

E.g. `subpackage` might have been updated with a chore: or refactor: commit, and we're expecting another commit or two to land before we want it to be released, so we do not bump the version in it's pyproject.toml yet. Simultaneously we have changes in `otherpackage`, bump it's version and run the release workflow. But now the release will fail, because it does not ignore `subpackage==1.0.0` and instead sees that the hash differs.

In my specific case, `subpackage` is actually just a standalone tool that i ship with my releases, so there is no real dependency between `subpackage` and `otherpackage` but i'd still like to just `uv build --all-packages` and `uv publish --index ...` and be done with it.

**Comment by konstin** [comment]
The docs are the reference for the expected behavior, the PR descriptions are mainly for internal review. The uv behavior is different from that of poetry: `--check-url` will only skip uploads if the file is exactly the same, to prevent the problems described in https://github.com/astral-sh/uv/issues/7917#issuecomment-2402208639. It currently does not support workflows such as the one you describe, where build and publish are called on any commit but should only actually upload when the version number changes. While this protects from a class of bugs around re-uploads and inconsistent index behaviors, it does unfortunately make CI pipelines more complex for the simple cases.

**Comment by linde12** [comment]
I see! So as i understand it there is no common way of handling this for the various repositories (artifactory, pypi, nexus etc.)? That is unfortunate, and i really don't think this issue has been solved then :/

OP specifically stated that he wished for something like poetry or twine `--skip-existing` flag which completely skips uploading of packages targeting the same version (AFAICT, i've used it before and it's been working great)

It looks to me like a "have problem A but solve a problem B" scenario 😅 

In a release workflow environment i (and everyone else using uv workspaces essentially) would have to manually implement logic that checks the versions on the remote index to determine whether or not a package should be published. I don't even see that as a reasonable option, at that point i'd rather bring in poetry/twine and more wisely spend the time developing actual features for my product.

FWIW while not ideal, twine seems to solve it by having some special handling for the various indexes.

Can this be considered, and if so should i create a new issue?

**Comment by konstin** [comment]
> I see! So as i understand it there is no common way of handling this for the various repositories (artifactory, pypi, nexus etc.)? That is unfortunate, and i really don't think this issue has been solved then :/

Unfortunately not, this will only be solved Upload API 2.0 (https://peps.python.org/pep-0694/). The current Upload API 1.0 is effectively undocumented, with every index implementing a slight variation of it. It also uploads one file at time and creates a release if the first file of a version is present, with different behaviors when re-uploading a file.

> FWIW while not ideal, twine seems to solve it by having some special handling for the various indexes.

Twine has made bad experiences with this feature, too, and has recently removed support for `--skip-exiting` for non-PyPI indices (https://github.com/pypa/twine/pull/1253). As poetry has copied twine's implementation (https://github.com/python-poetry/poetry/pull/2812), it's possible that poetry will follow suit and also remove support for this. There's a lot of complexity involved that makes it hard to support this cross-index without accidentally causing broken releases.

> Can this be considered, and if so should i create a new issue?

Feel free to open a new issue (it's better than bumping closed issues).

**Comment by davidbrochart** [comment]
As a workaround, instead of calling `uv publish` I use:
```bash
for filename in dist/*; do
    uv publish "$filename" || continue
done
```

**Comment by Sytten** [comment]
Also facing this issue, uv should check if the version already exists really. That is what most package managers do and I dont see the point of not doing that.
